# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(verbose_name='Journée métier (Europe/Istanbul)')),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('expected_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('declared_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('justification', models.TextField(blank=True, verbose_name="Justification de l'écart")),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Clôturée')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clôture quotidienne',
                'verbose_name_plural': 'Clôtures quotidiennes',
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('is_locked', models.BooleanField(default=False, verbose_name='Verrouillé (clôture en cours)')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cash_accounts', to='pricing.currency')),
            ],
            options={
                'verbose_name': 'Compte de caisse',
                'verbose_name_plural': 'Comptes de caisse',
            },
        ),
        migrations.CreateModel(
            name='CashHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handovers', to='cash.cashaccount')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_confirmed', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='handovers_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remise de caisse',
                'verbose_name_plural': 'Remises de caisse',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('movement_type', models.CharField(choices=[('OPERATION', 'Opération'), ('HANDOVER', 'Remise'), ('ADJUSTMENT', 'Ajustement'), ('OPENING', 'Ouverture de caisse')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='cash.cashaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-created_at'],
            },
        ),
    ]
