# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='operations.operation'),
        ),
        migrations.AddField(
            model_name='dailyclosure',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='closures', to='cash.cashaccount'),
        ),
        migrations.AddField(
            model_name='dailyclosure',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closures_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('agent', 'currency'), name='one_account_per_agent_currency'),
        ),
        migrations.AddConstraint(
            model_name='dailyclosure',
            constraint=models.UniqueConstraint(fields=('account', 'business_date'), name='one_closure_per_account_per_day'),
        ),
    ]
