# Generated by Django 5.2.17 on 2026-09-01 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_initial'),
        ('operations', '0001_initial'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='cash_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashhandover',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='handover_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='cash_movement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='cashmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('movement_type', 'OPERATION'), ('operation__isnull', False)), fields=('operation',), name='one_primary_movement_per_operation'),
        ),
    ]
