# Generated by Django 5.2.15 on 2026-09-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def activate_existing_cash_accounts(apps, schema_editor):
    apps.get_model("cash", "CashAccount").objects.update(is_active=True)


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0003_cashaccount_cash_balance_non_negative_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashaccount",
            name="allocated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Allouée le"
            ),
        ),
        migrations.AddField(
            model_name="cashaccount",
            name="allocated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cash_accounts_allocated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Allouée par",
            ),
        ),
        migrations.AddField(
            model_name="cashaccount",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Allouée et active"),
        ),
        migrations.RunPython(activate_existing_cash_accounts, migrations.RunPython.noop),
    ]
