# Generated by Django 5.2.17 on 2026-09-02 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_cash_accounts(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    CashAccount = apps.get_model("cash", "CashAccount")
    GlobalCashAccount = apps.get_model("cash", "GlobalCashAccount")
    administrator = User.objects.filter(role="ADMIN").order_by("pk").first()
    if not administrator:
        return
    for currency_id in CashAccount.objects.values_list("currency_id", flat=True).distinct():
        global_account, _ = GlobalCashAccount.objects.get_or_create(
            currency_id=currency_id,
            defaults={"administrator_id": administrator.pk, "balance": 0},
        )
        CashAccount.objects.filter(currency_id=currency_id, global_account__isnull=True).update(global_account=global_account)


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0005_cashfunding"),
        ("pricing", "0002_exchangerate_exchange_rate_positive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalCashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "administrator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="global_cash_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="global_cash_account",
                        to="pricing.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse globale",
                "verbose_name_plural": "Caisses globales",
            },
        ),
        migrations.AddField(
            model_name="cashaccount",
            name="global_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="agent_accounts",
                to="cash.globalcashaccount",
                verbose_name="Caisse globale source",
            ),
        ),
        migrations.RunPython(link_existing_cash_accounts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="globalcashaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("balance__gte", 0)),
                name="global_cash_balance_non_negative",
            ),
        ),
    ]
