# Generated by Django 5.2.17 on 2026-09-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_reserves(apps, schema_editor):
    GlobalCashAccount = apps.get_model('cash', 'GlobalCashAccount')
    GlobalCashMovement = apps.get_model('cash', 'GlobalCashMovement')
    for account in GlobalCashAccount.objects.exclude(balance=0).iterator():
        GlobalCashMovement.objects.create(
            global_account=account,
            direction='IN',
            movement_type='INITIAL',
            amount=account.balance,
            balance_after=account.balance,
            note='Solde existant repris lors de la création du grand livre global',
            created_by_id=account.administrator_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0006_globalcashaccount_cashaccount_global_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entrée'), ('OUT', 'Sortie')], max_length=3)),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Solde initial migré'), ('CAPITAL_IN', 'Apport de capital'), ('CAPITAL_OUT', 'Retrait de capital'), ('ALLOCATION', 'Allocation à une caisse agent'), ('HANDOVER', "Remise d'une caisse agent")], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('note', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='global_cash_movements', to=settings.AUTH_USER_MODEL)),
                ('funding', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='global_movement', to='cash.cashfunding')),
                ('global_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movements', to='cash.globalcashaccount')),
                ('handover', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='global_movement', to='cash.cashhandover')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse globale',
                'verbose_name_plural': 'Mouvements de caisse globale',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='global_cash_movement_amount_positive'), models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='global_cash_movement_balance_non_negative')],
            },
        ),
        migrations.RunPython(preserve_existing_reserves, migrations.RunPython.noop),
    ]
