# Generated by Django 5.2.17 on 2026-09-03 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_globalcashmovement'),
        ('operations', '0005_alter_operationrevision_operation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['account', '-created_at'], name='cash_account_date_idx'),
        ),
        migrations.AddIndex(
            model_name='globalcashmovement',
            index=models.Index(fields=['global_account', '-created_at'], name='global_cash_date_idx'),
        ),
    ]
