# Generated by Django 5.2.17 on 2026-09-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='clauses',
            field=models.TextField(blank=True, verbose_name='Clauses et conditions'),
        ),
    ]
