# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=40)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('DUE', 'Due'), ('PAID', 'Payée')], default='DUE', max_length=8)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='profits.allocation')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='distributions', to='stakeholders.stakeholder')),
            ],
        ),
        migrations.CreateModel(
            name='ProfitPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gross_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deductible_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('FINALIZED', 'Finalisée')], default='DRAFT', max_length=10)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.currency')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='profits.profitperiod'),
        ),
        migrations.AddConstraint(
            model_name='profitperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='profit_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='profitperiod',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date', 'currency'), name='unique_profit_period_currency'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('period', 'bucket'), name='unique_period_bucket'),
        ),
    ]
