# Generated by Django 5.2.17 on 2026-09-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_ledgermutex_servicecatalog_and_more'),
        ('profits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='approval_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_distribution', to='finance.journalbatch'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='payment_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='paid_distribution', to='finance.journalbatch'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='finance_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.financialperiod'),
        ),
        migrations.AddField(
            model_name='profitperiod',
            name='proposed_distribution',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
