# Generated by Django 5.2.15 on 2026-09-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profits", "0003_profitperiod_proposed_at_profitperiod_proposed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="status",
            field=models.CharField(
                choices=[
                    ("DUE", "Due"),
                    ("PAID", "Payée"),
                    ("REINVESTED", "Réinvestie dans le capital"),
                ],
                default="DUE",
                max_length=10,
            ),
        ),
    ]
