# Generated by Django 5.2.17 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profits", "0004_alter_distribution_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="profitperiod",
            name="distributable",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="profitperiod",
            name="prior_losses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
