# Generated by Django 5.2.17 on 2026-09-07 16:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0009_backfill_legacy_cash_ledgers'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        ('stakeholders', '0003_stakeholder_address_stakeholder_ended_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('service_code', models.CharField(blank=True, max_length=40)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('account_type', models.CharField(choices=[('AGENT_CASH', 'Caisse physique d’agent'), ('MOBILE_MONEY', 'Mobile money'), ('FINANCIAL_SERVICE', 'Service financier'), ('DIGITAL', 'Compte numérique'), ('CAPITAL', 'Capital'), ('COMMISSION', 'Commissions'), ('EXPENSE', 'Charges'), ('PARTNER_PAYABLE', 'Dette envers partenaire'), ('TRANSIT', 'Transit'), ('ADJUSTMENT', 'Régularisation')], max_length=24)),
                ('nature', models.CharField(choices=[('ASSET', 'Actif'), ('LIABILITY', 'Passif'), ('EQUITY', 'Capitaux propres'), ('INCOME', 'Produit'), ('EXPENSE', 'Charge')], max_length=12)),
                ('cached_balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('cutover_at', models.DateTimeField(blank=True, null=True)),
                ('ceiling', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_accounts', to='pricing.currency')),
                ('economic_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='financial_accounts', to='stakeholders.stakeholder')),
                ('legacy_cash_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='financial_account', to='cash.cashaccount')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='financial_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAY', 'Journalière'), ('WEEK', 'Hebdomadaire'), ('MONTH', 'Mensuelle')], max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('timezone_name', models.CharField(default='Europe/Istanbul', max_length=64)),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('LOCKED', 'Verrouillée')], default='OPEN', max_length=8)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', 'period_type'],
            },
        ),
        migrations.CreateModel(
            name='JournalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('effective_at', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('POSTED', 'Publié'), ('REVERSED', 'Contre-passé')], default='DRAFT', max_length=10)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='journal_batches_created', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='journal_batches_posted', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reversal', to='finance.journalbatch')),
            ],
            options={
                'ordering': ['-effective_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('DEBIT', 'Débit'), ('CREDIT', 'Crédit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='finance.financialaccount')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entries', to='finance.journalbatch')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='pricing.currency')),
            ],
            options={
                'ordering': ['batch_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyMigrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cutover_at', models.DateTimeField()),
                ('strategy', models.CharField(choices=[('OPENING_ONLY', 'Soldes d’ouverture uniquement'), ('HISTORY', 'Historique complet')], max_length=24)),
                ('status', models.CharField(choices=[('PREVIEW', 'Simulation'), ('APPLIED', 'Appliquée'), ('FAILED', 'Échec')], default='PREVIEW', max_length=8)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('migrated_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=18)),
                ('difference_origin', models.TextField(blank=True)),
                ('anomalies', models.JSONField(default=list)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.currency')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reconciliations', to='finance.financialaccount')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reconciliations', to='finance.legacymigrationrun')),
            ],
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.CheckConstraint(condition=models.Q(('ceiling__isnull', True), ('ceiling__gt', 0), _connector='OR'), name='finance_account_ceiling_positive'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='finance_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.UniqueConstraint(fields=('period_type', 'start_date', 'end_date'), name='unique_financial_period'),
        ),
        migrations.AddConstraint(
            model_name='journalbatch',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('source_model', ''), _negated=True), models.Q(('source_id', ''), _negated=True)), fields=('source_model', 'source_id', 'event_type'), name='unique_financial_source_event'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='accountreconciliation',
            constraint=models.UniqueConstraint(fields=('run', 'account'), name='unique_reconciliation_account_run'),
        ),
    ]
