# Generated by Django 5.2.17 on 2026-09-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_backfill_legacy_cash_ledgers'),
        ('finance', '0001_initial'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        ('stakeholders', '0004_alter_stakeholder_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerMutex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='legacy_global_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='cash.globalcashaccount'),
        ),
        migrations.AddField(
            model_name='journalbatch',
            name='payload_hash',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='legacymigrationrun',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legacymigrationrun',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='approved_finance_cutovers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legacymigrationrun',
            name='preview_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('AGENT_CASH', 'Caisse physique d’agent'), ('MOBILE_MONEY', 'Mobile money'), ('FINANCIAL_SERVICE', 'Service financier'), ('DIGITAL', 'Compte numérique'), ('CAPITAL', 'Capital'), ('COMMISSION', 'Commissions'), ('EXPENSE', 'Charges'), ('PARTNER_PAYABLE', 'Dette envers partenaire'), ('TRANSIT', 'Transit'), ('ADJUSTMENT', 'Régularisation'), ('GLOBAL_CASH', 'Caisse globale'), ('EXPENSE_PAYABLE', 'Charges à payer'), ('DISTRIBUTION_PAYABLE', 'Distributions à payer'), ('PARTNER_ADVANCE', 'Avances personnelles partenaire')], max_length=24),
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=120, unique=True)),
                ('payload', models.JSONField()),
                ('anomalies', models.JSONField(default=list)),
                ('resolution', models.TextField(blank=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='finance.servicecatalog'),
        ),
        migrations.CreateModel(
            name='AccountCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical', models.DecimalField(decimal_places=2, max_digits=18)),
                ('declared', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('justification', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.financialaccount')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='counts', to='finance.financialperiod')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('period', 'account'), name='unique_finance_period_count')],
            },
        ),
        migrations.CreateModel(
            name='EconomicRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COMMISSION', 'Part partenaire (%)'), ('REMUNERATION', 'Rémunération mensuelle'), ('DIVIDEND', 'Part du bénéfice distribuable (%)')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pricing.currency')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financial_rules', to='stakeholders.stakeholder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stakeholder', 'kind', 'effective_from'), name='unique_finance_rule_version')],
            },
        ),
    ]
