# Generated by Django 5.2.17 on 2026-09-10 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_ledgermutex_servicecatalog_and_more"),
        ("pricing", "0002_exchangerate_exchange_rate_positive_and_more"),
        ("profits", "0005_profitperiod_distributable_profitperiod_prior_losses"),
        ("stakeholders", "0005_stakeholder_canonical_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialaccount",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("AGENT_CASH", "Caisse physique d’agent"),
                    ("MOBILE_MONEY", "Mobile money"),
                    ("FINANCIAL_SERVICE", "Service financier"),
                    ("DIGITAL", "Compte numérique"),
                    ("CAPITAL", "Capital"),
                    ("COMMISSION", "Commissions"),
                    ("EXPENSE", "Charges"),
                    ("PARTNER_PAYABLE", "Dette envers partenaire"),
                    ("TRANSIT", "Transit"),
                    ("ADJUSTMENT", "Régularisation"),
                    ("GLOBAL_CASH", "Caisse globale"),
                    ("EXPENSE_PAYABLE", "Charges à payer"),
                    ("DISTRIBUTION_PAYABLE", "Distributions à payer"),
                    ("PARTNER_ADVANCE", "Avances personnelles partenaire"),
                    ("INVESTOR_FUNDS", "Fonds investisseurs"),
                    ("PARTNER_GUARANTEE", "Garanties partenaires"),
                    ("RETAINED_EARNINGS", "Résultats non distribués"),
                    ("FX_DIFFERENCE", "Écarts de change"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="DistributionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("EQUAL_SHARES", "Parts égales entre actionnaires actifs"),
                            ("RULE_PERCENT", "Pourcentages des règles datées"),
                        ],
                        max_length=16,
                    ),
                ),
                ("effective_from", models.DateField(unique=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from"],
            },
        ),
        migrations.CreateModel(
            name="FundContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_key", models.CharField(max_length=120, unique=True)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("SHAREHOLDER", "Apport actionnaire"),
                            ("INVESTOR", "Investissement"),
                            ("PARTNER_GUARANTEE", "Garantie partenaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("received_on", models.DateField()),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contribution",
                        to="finance.journalbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contributions_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pricing.currency",
                    ),
                ),
                (
                    "receiving_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="received_contributions",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="contributions",
                        to="stakeholders.stakeholder",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="contribution_amount_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="InternalTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_key", models.CharField(max_length=120, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "En transit"),
                            ("CONFIRMED", "Confirmé"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="INITIATED",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("initiated_at", models.DateTimeField()),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_confirmed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pricing.currency",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_in",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiation_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfer_initiation",
                        to="finance.journalbatch",
                    ),
                ),
                (
                    "settlement_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfer_settlement",
                        to="finance.journalbatch",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_out",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-initiated_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="transfer_amount_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fee__gte", 0)),
                        name="transfer_fee_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("source", models.F("destination")), _negated=True
                        ),
                        name="transfer_distinct_accounts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PartnerGuarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "per_operation_ceiling",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pricing.currency",
                    ),
                ),
                (
                    "stakeholder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="guarantee",
                        to="stakeholders.stakeholder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("per_operation_ceiling__gt", 0)),
                        name="guarantee_ceiling_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StakeholderRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REINVEST_PROFIT", "Réinvestir un bénéfice"),
                            ("WITHDRAW_PROFIT", "Retirer un bénéfice"),
                            ("INCREASE_INVESTMENT", "Augmenter l’investissement"),
                            ("WITHDRAW_INVESTMENT", "Retirer l’investissement"),
                            ("INCREASE_GUARANTEE", "Augmenter la garantie"),
                            (
                                "CONVERT_COMMISSION",
                                "Convertir des commissions en garantie",
                            ),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Soumise"),
                            ("APPROVED", "Validée"),
                            ("REJECTED", "Refusée"),
                            ("EXECUTED", "Exécutée"),
                        ],
                        default="SUBMITTED",
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_comment", models.CharField(blank=True, max_length=255)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pricing.currency",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "distribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests",
                        to="profits.distribution",
                    ),
                ),
                (
                    "execution_batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="executed_request",
                        to="finance.journalbatch",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests",
                        to="stakeholders.stakeholder",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="request_amount_positive",
                    )
                ],
            },
        ),
    ]
