# Generated by Django 5.2.17 on 2026-09-10 10:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_financialaccount_account_type_and_more"),
        ("stakeholders", "0005_stakeholder_canonical_identity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fundcontribution",
            name="evidence",
            field=models.FileField(
                blank=True, upload_to="private/contributions/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="fundcontribution",
            name="from_opening_balances",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="distributionpolicy",
            name="mode",
            field=models.CharField(
                choices=[
                    (
                        "EQUAL_SHARES",
                        "Parts égales entre les actionnaires sélectionnés",
                    ),
                    ("CAPITAL_PROPORTIONAL", "Proportionnelle aux apports en capital"),
                    ("RULE_PERCENT", "Pourcentages des règles datées (historique)"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="RemunerationTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                (
                    "partial_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PRORATA", "Prorata des jours"),
                            ("FULL", "Mois complet dû"),
                            ("NONE", "Rien n’est dû pour un mois incomplet"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "loss_month",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PAY", "Rémunération due même en mois déficitaire"),
                            ("SUSPEND", "Rémunération suspendue en mois déficitaire"),
                        ],
                        max_length=8,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stakeholder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="remuneration_terms",
                        to="stakeholders.stakeholder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrencyConversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("client_key", models.CharField(max_length=120, unique=True)),
                ("amount_source", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "amount_destination",
                    models.DecimalField(decimal_places=2, max_digits=18),
                ),
                ("rate_applied", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "reference_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "fee_source",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "realized_difference",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="conversion",
                        to="finance.journalbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="conversions_in",
                        to="finance.financialaccount",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="conversions_out",
                        to="finance.financialaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_destination__gt", 0),
                            ("amount_source__gt", 0),
                            ("rate_applied__gt", 0),
                        ),
                        name="conversion_amounts_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("fee_source__gte", 0)),
                        name="conversion_fee_non_negative",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DistributionPolicyShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=4, max_digits=7)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="finance.distributionpolicy",
                    ),
                ),
                (
                    "stakeholder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="distribution_shares",
                        to="stakeholders.stakeholder",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "stakeholder"),
                        name="unique_policy_shareholder",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gte", 0), ("percent__lte", 100)),
                        name="policy_share_percent_valid",
                    ),
                ],
            },
        ),
    ]
