# Generated by Django 5.2.17 on 2026-09-10 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_transfer_received_state'),
        ('operations', '0007_operation_supplier_fee_and_more'),
        ('stakeholders', '0005_stakeholder_canonical_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internaltransfer',
            name='return_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='return_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='transfer_returns_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internaltransfer',
            name='return_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PartnerCommissionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('GUARANTEE', 'Conversion automatique en garantie'), ('PAYABLE', 'Conserver dans Commissions à recevoir')], max_length=12)),
                ('effective_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='commission_choices', to='stakeholders.stakeholder')),
            ],
            options={
                'ordering': ['-effective_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CommissionConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='finance.journalbatch')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='automatic_commission_conversion', to='operations.operation')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='finance.partnercommissionchoice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='partnercommissionchoice',
            constraint=models.UniqueConstraint(fields=('stakeholder', 'effective_at'), name='unique_partner_choice_effect'),
        ),
    ]
