# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=40)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('XLSX', 'XLSX'), ('CSV', 'CSV')], max_length=4)),
                ('filters', models.JSONField(default=dict)),
                ('snapshot', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, upload_to='private/reports/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
