# Generated by Django 5.2.17 on 2026-09-02 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['requested_by', '-created_at'], name='report_owner_date_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexport',
            index=models.Index(fields=['status', 'created_at'], name='report_status_date_idx'),
        ),
    ]
