# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('SENT_TRANSFER', 'Transfert envoyé'), ('RECEIVED_TRANSFER', 'Transfert reçu'), ('WITHDRAWAL', 'Retrait')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='COMPLETED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_auto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Frais calculé (avant réduction)')),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fee_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='cash.cashaccount')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='pricing.currency')),
                ('tariff_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='operations', to='pricing.tariffschedule')),
            ],
            options={
                'verbose_name': 'Opération',
                'verbose_name_plural': 'Opérations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='operations.operation')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Révision d'opération",
                'verbose_name_plural': "Révisions d'opération",
                'ordering': ['-created_at'],
            },
        ),
    ]
