# Generated by Django 5.2.17 on 2026-09-01 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_cashaccount_cash_balance_non_negative_and_more'),
        ('operations', '0001_initial'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='operation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('fee__gte', 0)), name='operation_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('rate_to_usd__gt', 0)), name='operation_rate_positive'),
        ),
    ]
