# Generated by Django 5.2.17 on 2026-09-01 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operation_operation_amount_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='operation_requests', to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='request', to='operations.operation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('actor', 'key'), name='unique_operation_idempotency_key')],
            },
        ),
    ]
