# Generated by Django 5.2.15 on 2026-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0003_operationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="customer_identifier",
            field=models.CharField(
                default="", max_length=254, verbose_name="Numéro, e-mail ou identifiant"
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="customer_name",
            field=models.CharField(
                default="", max_length=180, verbose_name="Nom du client"
            ),
        ),
        migrations.AddField(
            model_name="operation",
            name="service",
            field=models.CharField(
                choices=[
                    ("AIRTEL_MONEY", "Airtel Money"),
                    ("VODACOM_MPESA", "Vodacom M-Pesa"),
                    ("AFRIMONEY", "Afrimoney"),
                    ("TAPTAP_SEND", "Tap Tap Send"),
                    ("PAYPAL", "PayPal"),
                    ("ORANGE_MONEY", "Orange Money"),
                ],
                default="AIRTEL_MONEY",
                max_length=24,
            ),
        ),
    ]
