# Generated by Django 5.2.17 on 2026-09-02 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0007_globalcashmovement'),
        ('operations', '0004_operation_customer_identifier_and_more'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationrevision',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='revisions', to='operations.operation'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['agent', '-created_at'], name='operation_agent_date_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', '-created_at'], name='operation_status_date_idx'),
        ),
    ]
