# Generated by Django 5.2.15 on 2026-09-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_alter_operationrevision_operation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="commission_owner_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
