# Generated by Django 5.2.17 on 2026-09-10 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0009_backfill_legacy_cash_ledgers"),
        ("operations", "0006_operation_commission_owner_confirmed"),
        ("pricing", "0002_exchangerate_exchange_rate_positive_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="supplier_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Frais fournisseur (charge FINCORYA)",
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=models.Q(("supplier_fee__gte", 0)),
                name="operation_supplier_fee_non_negative",
            ),
        ),
    ]
