# Generated by Django 5.2.17 on 2026-09-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0007_operation_supplier_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionServiceOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=24, unique=True, verbose_name="Code"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Nom affiché")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Service de transaction",
                "verbose_name_plural": "Services de transaction",
                "ordering": ["label"],
            },
        ),
    ]
