# Generated by Django 5.2.15 on 2026-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0009_seed_transaction_service_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="fee_mode",
            field=models.CharField(
                choices=[("ADDED", "Frais ajoutés"), ("DEDUCTED", "Frais déduits")],
                default="ADDED",
                max_length=10,
                verbose_name="Mode de frais",
            ),
        ),
    ]
