# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY'), ('GBP', 'GBP'), ('CDF', 'CDF')], max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_usd', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Taux vers USD')),
                ('effective_at', models.DateTimeField(verbose_name='En vigueur depuis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.currency')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-effective_at'],
            },
        ),
        migrations.CreateModel(
            name='TariffSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nom de la grille')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publiée')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tariff_schedules', to='pricing.currency')),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
            },
        ),
        migrations.CreateModel(
            name='TariffTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant minimum')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant maximum')),
                ('fixed_fee', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Frais fixe')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='pricing.tariffschedule')),
            ],
            options={
                'verbose_name': 'Tranche tarifaire',
                'verbose_name_plural': 'Tranches tarifaires',
                'ordering': ['schedule', 'min_amount'],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_amount__gte', models.F('min_amount'))), name='tier_max_gte_min')],
            },
        ),
    ]
