# Generated by Django 5.2.17 on 2026-09-01 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('rate_to_usd__gt', 0)), name='exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'effective_at'), name='unique_currency_rate_effective_at'),
        ),
        migrations.AddConstraint(
            model_name='tarifftier',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gt', 0)), name='tier_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='tarifftier',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0)), name='tier_fee_non_negative'),
        ),
    ]
