# Generated by Django 5.2.15 on 2026-09-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notificationdelivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationdelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("SENT", "Sent"),
                    ("RETRY", "Retry"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
