# Generated by Django 5.2.17 on 2026-09-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notification_notification_inbox_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekly_closure_weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lundi"),
                            (1, "Mardi"),
                            (2, "Mercredi"),
                            (3, "Jeudi"),
                            (4, "Vendredi"),
                            (5, "Samedi"),
                            (6, "Dimanche"),
                        ],
                        default=6,
                        verbose_name="Jour de clôture hebdomadaire",
                    ),
                ),
                (
                    "weekly_closure_time",
                    models.TimeField(
                        default="18:00", verbose_name="Heure de clôture hebdomadaire"
                    ),
                ),
                (
                    "reminder_hours_before",
                    models.PositiveSmallIntegerField(
                        default=2,
                        verbose_name="Rappel envoyé N heures avant la clôture",
                    ),
                ),
                (
                    "enable_weekly_agent_reminder",
                    models.BooleanField(
                        default=True, verbose_name="Rappel hebdomadaire — agents"
                    ),
                ),
                (
                    "enable_weekly_stakeholder_invite",
                    models.BooleanField(
                        default=True,
                        verbose_name="Invitation hebdomadaire — parties prenantes",
                    ),
                ),
                (
                    "enable_salary_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications salaires agents"
                    ),
                ),
                (
                    "enable_dividend_notifications",
                    models.BooleanField(
                        default=True,
                        verbose_name="Notifications dividendes actionnaires",
                    ),
                ),
                (
                    "enable_investor_notifications",
                    models.BooleanField(
                        default=True,
                        verbose_name="Notifications paiements investisseurs",
                    ),
                ),
                (
                    "enable_partner_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Notifications parts partenaires"
                    ),
                ),
                (
                    "enable_welcome_email",
                    models.BooleanField(
                        default=True,
                        verbose_name="E-mail de bienvenue à la création de compte",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paramètres de notification",
                "verbose_name_plural": "Paramètres de notification",
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Général (alerte interne)"),
                    ("WEEKLY_AGENT_REMINDER", "Rappel hebdomadaire agent"),
                    (
                        "WEEKLY_STAKEHOLDER_INVITE",
                        "Invitation hebdomadaire partie prenante",
                    ),
                    ("SALARY_INFO", "Salaire validé"),
                    ("SALARY_PAID", "Salaire payé"),
                    ("DIVIDEND_INFO", "Dividende validé"),
                    ("DIVIDEND_PAID", "Dividende payé"),
                    ("INVESTOR_DUE", "Rémunération investisseur due"),
                    ("INVESTOR_PAID", "Rémunération investisseur payée"),
                    ("PARTNER_SHARE_INFO", "Part partenaire validée"),
                    ("PARTNER_SHARE_PAID", "Part partenaire payée"),
                    ("WELCOME", "Bienvenue / activation de compte"),
                    ("TEST", "Envoi de test administrateur"),
                ],
                default="GENERAL",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="cta_label",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="notification",
            name="cta_url",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_key",
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="html_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["category", "-created_at"], name="notification_category_idx"
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
