# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('incurred_on', models.DateField()),
                ('receipt', models.FileField(blank=True, upload_to='private/expenses/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.currency')),
            ],
            options={
                'ordering': ['-incurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('ACCOUNTANT', 'Comptable'), ('ADMIN', 'Administrateur')], max_length=12)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approuvée'), ('REJECTED', 'Rejetée')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='expenses.expense')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expenseapproval',
            constraint=models.UniqueConstraint(fields=('expense', 'level'), name='one_expense_decision_per_level'),
        ),
    ]
