# Generated by Django 5.2.15 on 2026-09-02 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="salary_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Dépense générale"),
                    ("SALARY", "Salaire d'agent"),
                    ("RENT", "Loyer"),
                    ("OPERATIONS", "Charge opérationnelle"),
                    ("OTHER", "Autre"),
                ],
                default="GENERAL",
                max_length=16,
            ),
        ),
    ]
