# Generated by Django 5.2.17 on 2026-09-02 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_agent_expense_category'),
        ('pricing', '0002_exchangerate_exchange_rate_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', '-incurred_on'], name='expense_status_date_idx'),
        ),
    ]
