# Generated by Django 5.2.17 on 2026-09-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_expense_status_date_idx'),
        ('finance', '0001_initial'),
        ('stakeholders', '0004_alter_stakeholder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accrual_key',
            field=models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recognition_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recognized_expense', to='finance.journalbatch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='stakeholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='stakeholders.stakeholder'),
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_at', models.DateTimeField()),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='finance.journalbatch')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='expenses.expense')),
            ],
        ),
    ]
