# Generated by Django 5.2.17 on 2026-09-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_expense_accrual_key_expense_recognition_batch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("GENERAL", "Dépense générale"),
                    ("SALARY", "Salaire d'agent"),
                    ("RENT", "Loyer"),
                    ("OPERATIONS", "Charge opérationnelle"),
                    ("SUPPLIER_FEE", "Frais fournisseur"),
                    ("INVESTOR_RETURN", "Rémunération investisseur"),
                    ("OTHER", "Autre"),
                ],
                default="GENERAL",
                max_length=16,
            ),
        ),
    ]
