# Generated by Django 5.2.17 on 2026-09-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recoverycode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SUPERVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_agents', to=settings.AUTH_USER_MODEL, verbose_name='Superviseur rattaché'),
        ),
    ]
