# Generated by Django 5.2.17 on 2026-09-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('window_started', models.DateTimeField()),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('key_hash', 'action'), name='unique_auth_throttle_key')],
            },
        ),
    ]
