# Generated by Django 5.2.17 on 2026-09-01 17:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auththrottle'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_ended_on',
            field=models.DateField(blank=True, null=True, verbose_name="Fin d'activité agent"),
        ),
        migrations.AddField(
            model_name='user',
            name='agent_started_on',
            field=models.DateField(blank=True, null=True, verbose_name="Début d'activité agent"),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_salary_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_salary_usd__gte', 0)), name='user_salary_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('agent_ended_on__isnull', True), ('agent_started_on__isnull', True), ('agent_ended_on__gte', models.F('agent_started_on')), _connector='OR'), name='agent_employment_dates_valid'),
        ),
    ]
