# Generated by Django 5.2.15 on 2026-09-02 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def normalize_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(role__in=["SUPERVISOR", "ACCOUNTANT", "AUDITOR"]).update(role="ADMIN")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_agent_ended_on_user_agent_started_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=120, verbose_name="Ville"),
        ),
        migrations.RunPython(normalize_roles, migrations.RunPython.noop),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="agents/%Y/%m/", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("AGENT", "Agent"),
                    ("PARTNER", "Partenaire"),
                    ("INVESTOR", "Investisseur"),
                    ("SHAREHOLDER", "Actionnaire"),
                ],
                default="AGENT",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_agents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Superviseur rattaché",
            ),
        ),
    ]
