# Generated by Django 5.2.15 on 2026-09-02 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_city_user_photo_alter_user_role_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="supervisor",
        ),
    ]
