# Generated by Django 5.2.17 on 2026-09-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_user_supervisor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auththrottle",
            name="action",
            field=models.CharField(max_length=32),
        ),
    ]
