# Generated by Django 5.2.17 on 2026-09-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auththrottle_action_maxlength_32'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('FINANCE_MANAGER', 'Chargé des finances'), ('AGENT', 'Agent'), ('PARTNER', 'Partenaire'), ('INVESTOR', 'Investisseur'), ('SHAREHOLDER', 'Actionnaire')], default='AGENT', max_length=20, verbose_name='Rôle'),
        ),
    ]
