# Generated by Django 5.2.17 on 2026-09-01 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('type', models.CharField(choices=[('PARTNER', 'Partenaire'), ('INVESTOR', 'Investisseur'), ('SHAREHOLDER', 'Actionnaire')], max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_stakeholders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percent', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='partner_attribution', to='operations.operation')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partner_operations', to='stakeholders.stakeholder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('share_percent__gte', 0), ('share_percent__lte', 100)), name='partner_share_valid')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invested_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pricing.currency')),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='investments', to='stakeholders.stakeholder')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='investment_amount_positive')],
            },
        ),
    ]
