# Generated by Django 5.2.17 on 2026-09-02 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='dividend_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Pourcentage de dividende (%)'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='investor_return_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Rendement convenu (%)'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='partner_share_percent',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=7, verbose_name='Part partenaire (%)'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='payment_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('SEMIANNUAL', 'Semestrielle'), ('ANNUAL', 'Annuelle'), ('AT_MATURITY', "À l'échéance")], default='AT_MATURITY', max_length=16, verbose_name='Fréquence de paiement'),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='share_count',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name="Nombre d'actions"),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='share_unit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Valeur unitaire de l'action"),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False)), fields=('owner',), name='unique_stakeholder_owner'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('investor_return_percent__gte', 0)), name='stakeholder_return_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('share_count__gte', 0)), name='stakeholder_shares_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('share_unit_value__gte', 0)), name='stakeholder_share_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('dividend_percent__gte', 0), ('dividend_percent__lte', 100)), name='stakeholder_dividend_valid'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(('partner_share_percent__gte', 0), ('partner_share_percent__lte', 100)), name='stakeholder_partner_share_valid'),
        ),
    ]
