# Generated by Django 5.2.17 on 2026-09-07 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0002_stakeholder_dividend_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='started_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StakeholderRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SHAREHOLDER', 'Actionnaire'), ('INVESTOR', 'Investisseur'), ('PARTNER', 'Partenaire / associé'), ('AGENT', 'Agent'), ('OPERATOR', 'Opérateur / opératrice')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='economic_roles', to='stakeholders.stakeholder')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stakeholder', 'role', 'effective_from'), name='unique_party_role_effective_date'), models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='party_role_dates_valid')],
            },
        ),
    ]
