# Generated by Django 5.2.17 on 2026-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0003_stakeholder_address_stakeholder_ended_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='type',
            field=models.CharField(choices=[('PARTNER', 'Partenaire'), ('INVESTOR', 'Investisseur'), ('SHAREHOLDER', 'Actionnaire'), ('STAFF', 'Personnel')], max_length=12),
        ),
    ]
