# Generated by Django 5.2.17 on 2026-09-08 05:42

from django.db import migrations, models


def normalize_existing_identity(apps, schema_editor):
    Party = apps.get_model('stakeholders', 'Stakeholder')
    parties = [p for p in Party.objects.using(schema_editor.connection.alias).all()
               if ' '.join(p.name.split()).casefold() in {'mpoto jenovic', 'jenovic mpoto'}]
    if len(parties) > 1:
        raise RuntimeError('Identités Mpoto Jenovic en doublon : rapprocher les parties avant de migrer.')
    for party in parties:
        Party.objects.using(schema_editor.connection.alias).filter(pk=party.pk).update(
            name='Mpoto Jenovic', canonical_identity='mpoto-jenovic')


class Migration(migrations.Migration):

    dependencies = [
        ('stakeholders', '0004_alter_stakeholder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='canonical_identity',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
        migrations.RunPython(normalize_existing_identity, migrations.RunPython.noop),
    ]
